### ISSUE TITLE
ContainerDays 2020, June 22-24

### ISSUE THREAD

**Issue by mirabellaatloodse** [kris-nova/public-speaking#3]
**Name of the event**: ContainerDays

**Links to the event (main website, schedule, marketing, etc)**: https://www.containerdays.io/

**List of full days Nova would be needed**: Either June 23 or June 24

**City, Country**: Hamburg, Germany

**Any help with travel and lodging?**: Sure. We can coffer travel cost. 

**Anything else? Audience size? Why would I find this useful? What would you like for me to speak about?**: ContainerDays is a three days conference about containerization, microservices, Kubernetes and cloud native technologies. With 1100 participants, CDS is the largest container conference in Europe with plenty of networking opportunities in a relaxed atmosphere. You are one of the top speaker in the Kubernetes community and our attendees would love to hear you speaking at CDS.

**Comment by kris-nova** [comment]
Thanks - let me check this out and get back to you!
